// MarginaliaWatchWidgets.swift
// WidgetKit accessory complications for the Marginalia watch app — watchOS 10+
//
// Two accessory widgets, both reading data the paired iPhone mirrors over
// WatchConnectivity and the watch app persists into the shared App Group
// "group.io.marginalia.watch":
//
//   1. MarginaliaWatchPhrase  — the daily phrase ("frase scelta per te")
//        families: .accessoryRectangular, .accessoryInline
//   2. MarginaliaWatchReading — reading time this month + streak
//        families: .accessoryCircular, .accessoryInline, .accessoryRectangular
//
// Styling is watchOS-idiomatic: accessory complications render monochrome/tinted
// on most watch faces, so color is applied where allowed (the matcha accent) and
// .widgetAccentable() marks the parts that should pick up the user's tint.
// AccessoryWidgetBackground() gives the circular gauge its dimmed face ring.
//
// The Xcode extension target that builds this file is injected at CI time (the
// iOS project is regenerated by `flutter create` on every Codemagic build, so
// the target can't be committed).

import WidgetKit
import SwiftUI

// ─── Shared App Group ──────────────────────────────────────────────────────────

private let kAppGroup = "group.io.marginalia.watch"

private func sharedDefaults() -> UserDefaults? {
    UserDefaults(suiteName: kAppGroup)
}

// Read an Int defensively — the value may be stored as Int, NSNumber or String.
private func intValue(_ defaults: UserDefaults?, _ key: String) -> Int {
    guard let object = defaults?.object(forKey: key) else { return 0 }
    if let i = object as? Int { return i }
    if let n = object as? NSNumber { return n.intValue }
    if let s = object as? String, let i = Int(s) { return i }
    return 0
}

// ─── Brand palette ───────────────────────────────────────────────────────────

private extension Color {
    static let mPrimary = Color(red: 0.227, green: 0.400, blue: 0.141) // #3A6624 matcha
    static let mAccent  = Color(red: 0.290, green: 0.478, blue: 0.204) // #4A7A35
}

// Refresh roughly every 2 hours; the watch app also force-reloads timelines the
// moment a fresh application context arrives, so this is just a safety cadence.
private func nextRefreshDate() -> Date {
    Calendar.current.date(byAdding: .hour, value: 2, to: Date())
        ?? Date().addingTimeInterval(2 * 60 * 60)
}

// Format minutes as a compact, human label.
private func minutesLabel(_ m: Int) -> String {
    if m < 60 { return "\(m) min" }
    let h = m / 60, r = m % 60
    return r == 0 ? "\(h)h" : "\(h)h \(r)m"
}

// ════════════════════════════════════════════════════════════════════════════
//  WIDGET 1 — Daily phrase
// ════════════════════════════════════════════════════════════════════════════

struct PhraseEntry: TimelineEntry {
    let date: Date
    let text: String
    let book: String

    static let placeholder = PhraseEntry(
        date: Date(),
        text: "Non si leggono i libri per finirli, ma per abitarli.",
        book: "Come un romanzo"
    )
}

struct PhraseProvider: TimelineProvider {
    func placeholder(in context: Context) -> PhraseEntry { .placeholder }

    func getSnapshot(in context: Context, completion: @escaping (PhraseEntry) -> Void) {
        completion(entry())
    }

    func getTimeline(in context: Context, completion: @escaping (Timeline<PhraseEntry>) -> Void) {
        completion(Timeline(entries: [entry()], policy: .after(nextRefreshDate())))
    }

    private func entry() -> PhraseEntry {
        let d = sharedDefaults()
        let text = d?.string(forKey: "w_text")
        let book = d?.string(forKey: "w_book")
        return PhraseEntry(
            date: Date(),
            text: (text?.isEmpty == false) ? text! : PhraseEntry.placeholder.text,
            book: book ?? ""
        )
    }
}

struct PhraseWidgetView: View {
    @Environment(\.widgetFamily) private var family
    let entry: PhraseEntry

    var body: some View {
        switch family {
        case .accessoryInline:
            // A single short line; system clips it to fit.
            Text(entry.text)

        case .accessoryRectangular:
            VStack(alignment: .leading, spacing: 2) {
                Text(entry.text)
                    .font(.system(size: 14, weight: .regular, design: .serif))
                    .lineLimit(book.isEmpty ? 3 : 2)
                    .minimumScaleFactor(0.85)
                if !book.isEmpty {
                    Text(book)
                        .font(.system(size: 11, weight: .medium))
                        .foregroundStyle(.secondary)
                        .lineLimit(1)
                        .widgetAccentable()
                }
            }
            .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .leading)
            .containerBackground(.ultraThinMaterial, for: .widget)

        default:
            Text(entry.text)
                .containerBackground(.ultraThinMaterial, for: .widget)
        }
    }

    private var book: String { entry.book }
}

struct MarginaliaWatchPhrase: Widget {
    let kind = "MarginaliaWatchPhrase"

    var body: some WidgetConfiguration {
        StaticConfiguration(kind: kind, provider: PhraseProvider()) { entry in
            PhraseWidgetView(entry: entry)
        }
        .configurationDisplayName("Frase del momento")
        .description("La frase scelta per te.")
        .supportedFamilies([.accessoryRectangular, .accessoryInline])
    }
}

// ════════════════════════════════════════════════════════════════════════════
//  WIDGET 2 — Reading time
// ════════════════════════════════════════════════════════════════════════════

struct ReadingEntry: TimelineEntry {
    let date: Date
    let monthMinutes: Int
    let streak: Int

    static let placeholder = ReadingEntry(date: Date(), monthMinutes: 240, streak: 7)
}

struct ReadingProvider: TimelineProvider {
    func placeholder(in context: Context) -> ReadingEntry { .placeholder }

    func getSnapshot(in context: Context, completion: @escaping (ReadingEntry) -> Void) {
        completion(entry())
    }

    func getTimeline(in context: Context, completion: @escaping (Timeline<ReadingEntry>) -> Void) {
        completion(Timeline(entries: [entry()], policy: .after(nextRefreshDate())))
    }

    private func entry() -> ReadingEntry {
        let d = sharedDefaults()
        return ReadingEntry(
            date: Date(),
            monthMinutes: intValue(d, "w_month_min"),
            streak: intValue(d, "w_streak")
        )
    }
}

struct ReadingWidgetView: View {
    @Environment(\.widgetFamily) private var family
    let entry: ReadingEntry

    var body: some View {
        switch family {
        case .accessoryCircular:
            ZStack {
                AccessoryWidgetBackground()
                VStack(spacing: 0) {
                    Text("\(entry.monthMinutes)")
                        .font(.system(size: 20, weight: .semibold, design: .rounded))
                        .minimumScaleFactor(0.5)
                        .lineLimit(1)
                    Text("min")
                        .font(.system(size: 11, weight: .medium))
                        .foregroundStyle(.secondary)
                }
            }
            .widgetAccentable()
            .containerBackground(.ultraThinMaterial, for: .widget)

        case .accessoryInline:
            // Inline supports a leading SF Symbol via Label.
            Label("\(entry.monthMinutes)m", systemImage: "book.closed")

        case .accessoryRectangular:
            VStack(alignment: .leading, spacing: 2) {
                Label("Lettura", systemImage: "book.closed")
                    .font(.system(size: 13, weight: .semibold))
                    .foregroundStyle(Color.mAccent)
                    .widgetAccentable()
                Text("\(minutesLabel(entry.monthMinutes)) questo mese")
                    .font(.system(size: 13, weight: .regular))
                Text("Streak \(entry.streak) giorni")
                    .font(.system(size: 12, weight: .regular))
                    .foregroundStyle(.secondary)
            }
            .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .leading)
            .containerBackground(.ultraThinMaterial, for: .widget)

        default:
            Text(minutesLabel(entry.monthMinutes))
                .containerBackground(.ultraThinMaterial, for: .widget)
        }
    }
}

struct MarginaliaWatchReading: Widget {
    let kind = "MarginaliaWatchReading"

    var body: some WidgetConfiguration {
        StaticConfiguration(kind: kind, provider: ReadingProvider()) { entry in
            ReadingWidgetView(entry: entry)
        }
        .configurationDisplayName("Lettura del mese")
        .description("Minuti letti questo mese e streak.")
        .supportedFamilies([.accessoryCircular, .accessoryInline, .accessoryRectangular])
    }
}

// ════════════════════════════════════════════════════════════════════════════
//  Bundle entry point
// ════════════════════════════════════════════════════════════════════════════

@main
struct MarginaliaWatchWidgets: WidgetBundle {
    var body: some Widget {
        MarginaliaWatchPhrase()
        MarginaliaWatchReading()
    }
}
