// MarginaliaWatchApp.swift
// Marginalia — watchOS companion app (single-target SwiftUI app, watchOS 10+)
//
// Purpose
// ───────
// A small on-wrist surface that shows the daily phrase ("frase scelta per te")
// and a glance at this month's reading time, on-brand with the matcha palette.
//
// Data flow
// ─────────
// The paired iPhone pushes a WatchConnectivity *application context* (a compact
// key/value snapshot — latest-value-wins, survives until replaced). This app's
// WCSessionDelegate writes every value into the watch-side App Group
// UserDefaults ("group.io.marginalia.watch") and then kicks the WidgetKit
// complications to reload. The complication extension reads the SAME App Group,
// so it stays in sync without its own connectivity session.
//
// This file is committed but the Xcode watch-app target that builds it is
// injected at CI time (the iOS project is regenerated by `flutter create` on
// every Codemagic build, so the target can't be committed).

import SwiftUI
import WatchConnectivity
import WidgetKit

// ─── Shared App Group ──────────────────────────────────────────────────────────
// NOTE: the watch app uses its OWN App Group ("group.io.marginalia.watch"),
// distinct from the iOS home-widget group — App Groups are not shared across the
// phone/watch boundary, so the phone mirrors the data over WatchConnectivity and
// this app re-persists it locally for the complications to read.

enum WatchStore {
    static let appGroup = "group.io.marginalia.watch"

    // Keys written by this app, read by the complications.
    static let kText      = "w_text"        // String  — the phrase
    static let kBook      = "w_book"        // String  — book title
    static let kAuthor    = "w_author"      // String  — author
    static let kMonthMin  = "w_month_min"   // Int     — reading minutes this month
    static let kStreak    = "w_streak"      // Int     — day streak
    static let kUpdated   = "w_updated"     // String  — ISO8601 timestamp

    static var defaults: UserDefaults? { UserDefaults(suiteName: appGroup) }
}

// ─── Brand palette ───────────────────────────────────────────────────────────

extension Color {
    static let mInk     = Color(red: 0.106, green: 0.149, blue: 0.106) // #1B261B
    static let mPaper   = Color(red: 0.980, green: 0.980, blue: 0.969) // #FAFAF7
    static let mPrimary = Color(red: 0.227, green: 0.400, blue: 0.141) // #3A6624 matcha
    static let mAccent  = Color(red: 0.290, green: 0.478, blue: 0.204) // #4A7A35
    static let mMuted   = Color(red: 0.435, green: 0.459, blue: 0.431) // #6F756E
}

// ─── WatchConnectivity session manager ─────────────────────────────────────────

final class WatchSessionManager: NSObject, ObservableObject, WCSessionDelegate {

    /// Mirror of the App Group values, published so ContentView re-renders the
    /// instant a fresh application context arrives (no need to relaunch).
    @Published var text: String = ""
    @Published var book: String = ""
    @Published var author: String = ""
    @Published var monthMinutes: Int = 0
    @Published var streak: Int = 0

    override init() {
        super.init()
        loadFromDefaults()
        if WCSession.isSupported() {
            let session = WCSession.default
            session.delegate = self
            session.activate()
        }
    }

    // Seed the published state from whatever is already persisted, so the UI has
    // content on cold launch before any new context arrives.
    private func loadFromDefaults() {
        let d = WatchStore.defaults
        text = d?.string(forKey: WatchStore.kText) ?? ""
        book = d?.string(forKey: WatchStore.kBook) ?? ""
        author = d?.string(forKey: WatchStore.kAuthor) ?? ""
        monthMinutes = WatchSessionManager.intValue(d, WatchStore.kMonthMin)
        streak = WatchSessionManager.intValue(d, WatchStore.kStreak)
    }

    /// Read an Int defensively: the value may arrive as Int, NSNumber or String.
    static func intValue(_ defaults: UserDefaults?, _ key: String) -> Int {
        guard let object = defaults?.object(forKey: key) else { return 0 }
        if let i = object as? Int { return i }
        if let n = object as? NSNumber { return n.intValue }
        if let s = object as? String, let i = Int(s) { return i }
        return 0
    }

    // MARK: WCSessionDelegate

    func session(_ session: WCSession,
                 activationDidCompleteWith activationState: WCSessionActivationState,
                 error: Error?) {
        // No-op beyond logging: once active, the phone may immediately deliver the
        // most recent application context, handled below.
        if let error = error {
            NSLog("Marginalia watch: WCSession activation error: \(error.localizedDescription)")
        }
    }

    func session(_ session: WCSession,
                 didReceiveApplicationContext applicationContext: [String: Any]) {
        store(applicationContext)
    }

    /// Persist each provided value into the App Group and refresh complications.
    private func store(_ context: [String: Any]) {
        guard let d = WatchStore.defaults else { return }

        func putString(_ key: String) {
            if let value = context[key] as? String {
                d.set(value, forKey: key)
            }
        }
        func putInt(_ key: String) {
            if let object = context[key] {
                if let i = object as? Int {
                    d.set(i, forKey: key)
                } else if let n = object as? NSNumber {
                    d.set(n.intValue, forKey: key)
                } else if let s = object as? String, let i = Int(s) {
                    d.set(i, forKey: key)
                }
            }
        }

        putString(WatchStore.kText)
        putString(WatchStore.kBook)
        putString(WatchStore.kAuthor)
        putString(WatchStore.kUpdated)
        putInt(WatchStore.kMonthMin)
        putInt(WatchStore.kStreak)

        // Refresh the in-memory mirror on the main thread (this delegate callback
        // can arrive off-main) so the SwiftUI view updates immediately.
        DispatchQueue.main.async {
            self.loadFromDefaults()
            WidgetCenter.shared.reloadAllTimelines()
        }
    }
}

// ─── App entry point ───────────────────────────────────────────────────────────

@main
struct MarginaliaWatchApp: App {
    @StateObject private var session = WatchSessionManager()

    var body: some Scene {
        WindowGroup {
            ContentView()
                .environmentObject(session)
        }
    }
}

// ─── Root view ─────────────────────────────────────────────────────────────────

struct ContentView: View {
    @EnvironmentObject private var session: WatchSessionManager

    private var phrase: String {
        session.text.isEmpty
            ? "Apri Marginalia sull'iPhone per ricevere la tua frase del giorno."
            : session.text
    }

    private var minutesLine: String {
        let m = session.monthMinutes
        if m <= 0 { return "Nessuna lettura questo mese" }
        return "\(m) min questo mese"
    }

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 10) {

                // Brand header
                HStack(spacing: 6) {
                    RoundedRectangle(cornerRadius: 5, style: .continuous)
                        .fill(Color.mPrimary)
                        .frame(width: 18, height: 18)
                        .overlay(
                            Text("M")
                                .font(.system(size: 11, weight: .bold, design: .serif))
                                .foregroundStyle(.white)
                        )
                    Text("Marginalia")
                        .font(.system(size: 13, weight: .semibold))
                        .foregroundStyle(.secondary)
                }

                // The daily phrase
                Text(phrase)
                    .font(.system(size: 16, weight: .regular, design: .serif))
                    .italic()
                    .foregroundStyle(.primary)
                    .lineSpacing(3)
                    .fixedSize(horizontal: false, vertical: true)

                // Book attribution (only when present)
                if !session.book.isEmpty {
                    Text(session.author.isEmpty ? session.book : "\(session.book) · \(session.author)")
                        .font(.system(size: 11, weight: .medium))
                        .foregroundStyle(.secondary)
                        .lineLimit(2)
                }

                Divider()
                    .overlay(Color.mMuted.opacity(0.4))

                // Reading time glance
                HStack(spacing: 6) {
                    Image(systemName: "book.closed")
                        .font(.system(size: 12, weight: .semibold))
                        .foregroundStyle(Color.mAccent)
                    Text(minutesLine)
                        .font(.system(size: 12, weight: .medium))
                        .foregroundStyle(Color.mAccent)
                }

                if session.streak > 0 {
                    Text("Streak \(session.streak) giorni")
                        .font(.system(size: 11, weight: .regular))
                        .foregroundStyle(.secondary)
                }
            }
            .frame(maxWidth: .infinity, alignment: .leading)
            .padding(.horizontal, 4)
        }
    }
}
