// MarginaliaWidgets.swift
// WidgetKit extension for Marginalia — iOS 17+
//
// Two home-screen widgets, both reading data the Flutter app writes into the
// shared App Group "group.marginalia.widget" (via the home_widget package):
//
//   1. MarginaliaPhraseWidget  — the "frase scelta per te" (daily highlight)
//   2. MarginaliaStatsWidget    — reading stats (streak, minutes, books)
//
// Styling: a translucent "liquid glass" look built on .ultraThinMaterial over a
// soft matcha gradient, with .containerBackground(for: .widget) so it composites
// correctly on the home screen and adapts to the iOS 18 tinted/clear modes.
// System serif is used for the quote (no bundled fonts required).
//
// The Xcode target that builds this file is injected at CI time by
// ios/scripts/add_widgets_extension.rb (the iOS project is regenerated by
// `flutter create` on every Codemagic build, so the target can't be committed).

import WidgetKit
import SwiftUI
import UIKit

// ─── Shared App Group ──────────────────────────────────────────────────────────

private let kAppGroup = "group.marginalia.widget"

private func sharedDefaults() -> UserDefaults? {
    UserDefaults(suiteName: kAppGroup)
}

// ─── Brand palette ───────────────────────────────────────────────────────────

private extension Color {
    static let mInk     = Color(red: 0.106, green: 0.149, blue: 0.106) // #1B261B
    static let mPaper   = Color(red: 0.980, green: 0.980, blue: 0.969) // #FAFAF7
    static let mPrimary = Color(red: 0.227, green: 0.400, blue: 0.141) // #3A6624 matcha
    static let mAccent  = Color(red: 0.290, green: 0.478, blue: 0.204) // #4A7A35
    static let mMuted   = Color(red: 0.435, green: 0.459, blue: 0.431) // #6F756E
    // Scripta brand mark palette (sage layered cards + red bookmark).
    static let sCream   = Color(red: 0.945, green: 0.933, blue: 0.906) // #F1EEE7
    static let sSage    = Color(red: 0.753, green: 0.812, blue: 0.698) // #C0CFB2
    static let sSageDeep = Color(red: 0.561, green: 0.647, blue: 0.494) // deeper sage
    static let sRed     = Color(red: 0.725, green: 0.290, blue: 0.255) // #B94A41
}

// A soft brand gradient that sits *under* the frosted material to give the glass
// a faint colored tint without becoming opaque.
private struct GlassTint: View {
    var body: some View {
        LinearGradient(
            colors: [
                Color.mPrimary.opacity(0.22),
                Color.mAccent.opacity(0.10),
                Color.mPaper.opacity(0.04),
            ],
            startPoint: .topLeading,
            endPoint: .bottomTrailing
        )
    }
}

// ─── Scripta "S" badge ──────────────────────────────────────────────────────

private struct BrandMark: View {
    var label: String? = nil

    var body: some View {
        HStack(spacing: 6) {
            ScriptaLogo()
                .frame(width: 22, height: 22)
            if let label {
                Text(label)
                    .font(.system(size: 11, weight: .medium))
                    .foregroundStyle(.secondary)
                    .lineLimit(1)
            }
        }
    }
}

// ─── Scripta logo (embedded raster) ───────────────────────────
// The brand mark is bundled as a base64 PNG inside this committed source file,
// so the per-build widget-target regeneration in CI can never drop it (no
// asset-catalog entry required). Transparent, so it sits on any surface.
private struct ScriptaLogo: View {
    var body: some View {
        if let img = scriptaLogoImage {
            Image(uiImage: img).resizable().aspectRatio(contentMode: .fit)
        } else {
            Color.clear
        }
    }
}

private let scriptaLogoImage: UIImage? = {
    guard let data = Data(base64Encoded: scriptaLogoPNGBase64),
          let img = UIImage(data: data) else { return nil }
    return img
}()

private let scriptaLogoPNGBase64 = "iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAA+iUlEQVR42u29abAk13Ue+J17b2bW+rZegAYaOwGQDZCgRYrUwiG6aU3EjEUqJiamEeNQ2BMeeTijsGmZIzGszfG6PZbMMS1ZDnJIQaJFUhKDdrclRShCoZE4M40OiBLFRQIpoomNIPZu9PLW2nK598yPzKzK5WZW1utuEpJQiMJ7Xa+qMvPmuWf5zjnfAV5/vP54/fH64/XH64/XH68//vY96Lt9AsxMJ06coBMnTuD06dN04MABev22VD+OXrrEOH6cT5w4gRMnTjAR8d+ai2dmYmZx5swZdebMGcXMrwvLtVlTmayn+E6vqfpOaLlTp06JAwcOEBFFABiASf/4kY98pHvHHXfsX17urHW77X1KqSUhZF+S6DOjBSEcgNkYPVsYUziCELD/zVhORzQ8bTPn78LyvuxrwnaiDY4hkktiBoiMMRERJkQY6yjaCo3eCkeTjckw2Hzx0hOXiWgXgM5+w5kzZ9SlS5f4oYceMsl6//UzYclOEEQ0vbgjR464Dz/8sTcvLa1+X7vd/l7P896kpLpFKbXWarW8dqcDx3FeC5b1tapvEAYBxqMRJpNxGEXRho6iFyf+5NxgNP7izs7mF3/yJ3/6G1/96lfDzH2QAMz1MnV0nYRHZgRHPProoz9w4MDq/9Dr9f9er9u/e3llNbcorCNoHcEwG2bD8YucbB3O7yGafsyyvIW3kf09lPkHF97PmTcUDzX9N1u/rXS84nFqTt3+ucxFEFHyg4hIkJSShMxvts2NyxgMBk8NhsM/vHx54/fe/e53P5qqucI9eW0K0Pr6ujhx4gSIyLz3ve/trK//y3948OAN/9u+tdUHur0lAEAUjmG0jrTRYGPIsBEAgSg5F66/IQzKvcy5G1n8ab/IvW5FoukGWXA5uUYcMf/sch/hVIA5WQ0WUhopJKSUSjptAMBwsI2NKxuPXbp4+RMf/shHfuv06dNjZhYnTpzAyZMnzWtOgLISfvbs2R+9/fbbfv7WW299I0AI/CGHUaiNNiIxa5V3tXZ5KStIye/cUCBoka1vuXG84IryAsegBaXa8h0MTlWjkUIapRzptroEGLz4wvNPPPf8S7/47ne/+7eutTa6Jk70mTNnFBFFn/70p+965zu/9z/c/Ya7f1gqB5PxIArDQIAgiEiREHN3G1ETTyDzOy248EVlQA1vFF2nrUmzn9Twmm0vEihdPKGZhQ58+IFvHMfhW26944033XTzb577xjf+/he/9KWfIKKnz5w5o44dOxZ9tzUQMbMgIv3Hf/zHx++//75fPXTopjV/MtBB4BOREFmJoIwavp4qkRsoB9qjSaM9mMC6Y1GTBeCKzxe0tvV9iVbyvBa7Xkeef+XlrSe/+cQHjv3QD/32qVOn5PHjx6/KwaarjLKIiMwXvvDoiQceeOt6t9vGYHdHAyyJRP5SqOgc2g9ONMeFqD2nZj6M7fv3IhRM1y5IbqJ5befJpb9RRrBm72bDEES621+So+EQX3vsrz78A+9618+kuNFehYiuVnj+/M+/+PA73vGO90ehr0ejoZBS0NTdTQWFuCIyouYnQAuqm8rPUs2WbmD2rtYTv2YBfdlj5KxW4vj1osNvjOFOu22k48q//IvHPvtvPvxv/6dTp04xgD2h2mIvQvfII49IIjJ/9md/+h/f8Y53vj8IxuF4PJRSSmLOSz6hLDw0/a9qabj6Za57m+VFmh1xoTtPWf+EFhMewt6knRbd+ZRXP8yFv3Np6UgIGo3HMgz88O98z9t/9F986Kd+i4gMgD2h2GoPDrM8duxY9OjZR375+77v+/9n3x+Gge87QohYcFJTRTwVmiweQvlfataYr0LrZHYmJ6Haot/DV6Fu2PKZoqNS6+vMc6eprEvTdWYuOeep9HD6OSEw8ScOwOHbvvdtf/9P/uTRTSL6J2fOnFEAoutmwlLP/Q//8A/+yXve856PEZlwMh47IhddxRcgsuaLq29CDJAxmsUgVB9m10VX9J03PWz1dAkETqLHGLmkTDTZxKjzXJeeSu83BSGK/SKDdrsVMpPzhT/54oeO/d2/++8Wjc4am7BTp07JY8eORZ/97Gff8cADb/kPUpKejEYqFp4Ug+BE88+UJjOD05/J79mLjl+f/Zyq4tyz/DqDwZT8RP4Y0/OZPk3y5IJCLzzT7577NHOeyXlkz316zWaG2bBJXN3ZtXOD4+eviwHD4OwzfT3zpKl1mK0/CYHxeKIcJaJ73viGf/v7v//733/s2LHo1KlT8pqasMQ28gc/+MH2A2858puHDh2Sg90tLaSg2U3JLFRxY7AFMyP7XuG9xOpchc1l9ipTKdVhx/DyaDZXHZgrHGyuU3P1NpPRLNIsBiNcNH3MidmminiAMkJENBgMxU03HaKNja3PPPzww28F4DMzNXGqG/pApwXRQ/rMmf93/b7733zveLgTCUDN8lVATjnWhMXMBCKLZm9qW5sAOMRTXVh8a7qsBlVyTnn/yWo2EtHiCjym8Nnct1SeP1nEuAyFsyW/xhbjx2zN4lmNHhHEZDSM7r//yN0bG1s/9+CDD/5ckoTVVy1AzCwAmN/+5G/fdtedd3xQh77RkZYkqOywZTdmYSdSRmpseM28KJmoLAlclepgqv0ubupDc7WHMb0VVIbEa2FSbgBIcvpWCxTOif/ERR3LFeKRCGKygOl94cJ2iKJQQof69ttu/uDnPve53wDwbAISm6vygU6fPk1ExHcduf3/uOXWW1x/MmYSRDYpmC46WwWxsCBcHYCz/a4zV0f52c8xF76m3uWpcrMKhyELokBgTp4NTq1YCVRy9bLnwhUuW87LpNyzHH6lsk3WfCLlrAfRaDzCrbfd2r718OFfICI+ffo0XZUTferUKfnQQw/p3/md33ng5ptv+gfBZGwMs8ykgytNfuoYclagSovF9ptbuFPE1TgQZX5SdmFyB8/7abaXYXHl4vemQlK+0VUm2vpey7/zt5Kse8cq+1y7f9LwZWbGi0FKBbRmDMvQH5vDh286/nu/93tvfuihh/Q8h7pWgI4fPw4AuPHGGz9w+PDNiKLQUM6Pz5yITTAKC1uSuGwWmbl8M7kin8kVey13IolQZVfJ1G35spbjzPeVhN2mQUx54/C8Q+YirArtWKGdqp80Pffsd+d/L2tjAhCFkbnl1pvF/v0HfxwA5tWoi7rIi4j0r//6r6+triz991EUQGst8yF40XSkATUqohfOoKbFcoyZjTZmFg4bY2C0zjwN2JhCWIucWqAUe6YZBk1cBpmt2qqsIuw7vOLmNg4jeY+YFDf/4upD2N0HZkBrLdhorK0tvW99fb117NixqA6hrnSiH3nkEQkguuWWW47dfPNNq2EYaiKSXFtS0KBcqgC3x/aZplEHGwMQwRgNAkEqCZBIK/JmgpvBRMwU40kR2bi0IUXEZ64iJeKdr50g5gp8sui3XcMU/XWALJv8lWpggzSw9/2JOXTDwcNvf/vbHwTwR6dPnxZVEdncKGx5uf/fLvW7PBgMmC11A1wBVnAxMKb4pgqyF9kwM4w2gCDsvvwKvvG5/wwd+FDdHtxeD+2VFXjLy2gtLaHV78PpduF22lDtFpTrghwHQkqQyGS9EtAPJgMAWjL8VAr18k5nPiFZCAeJaurvuZhnKERU109o9vwpArQ2ZnV1hfbtW30XgD+qM2OVAvSe97wnev/73+/0u92j2mgyzIKa1Ewkki0IEFJBiNj3iSKNMAgRhiGMjgBmCBKQUkEqBSlljJiSwIuP/gm2v/GXgAF0FMU3UEoQCZCUEK4LcjxI14NsebEwLS3BXVqCt7yE1tISvH4fXr8Ht9uD02lDeR6U50EoBSEFIGKtlkOXTSL4yTUaZggpS2Em19SQUKPb9tpu5TKGCQRa6vV/EACOHj1qFhKgNP7/kR/5kbcsLy/d6fs+U6W/lE9CCRELhdEau9s72LhyBVtbWxhNRtA6AhsDYxjGRDAmDkAFEZRy4CgHpA3MS8+jv7YGaAM2Ogf8MJvYLwqHiCY78DcNxlonflGCnZAAhAQpBeF5kK0WnE4Xbq8Ht9+H1+vFwtbvwuv34fZ6sRB2O3A6HUivBek66LbbGA9Hibcoy/gg11Sq5arz+fr1MVDDeup51ft5DEUEvo9Ot/W2X/zoR/cR0ZUqZFpV+D8CgGm1Wnevrq0QAREIqoj9J40CYGYIQVDSwWTi44Xnn8cr51/CaDKC8hx0ul30DyzB9VyoZEenEYiOIugwQhQECIMQ44tX4IQhpOeBTGx+SjlUjn2lNP8Vf1nsWE/NldHQ2oD1BGZnhGjrCkJjsMsGhgGd4lJSgpQD1WrB6XbhdGPhctotvOQH+K//4Y+i01+Kozol82g7FeC4rAWkmnpYvnalfVSqcMtXfTY+VPZaiCgKA7O6srL0wJ13PgDg/6vyg2p9oF6vc3/LczGZTBL1w6W4mZnhKIUo0njm20/j+Re+DXIFVvcfwA1LhwEBhFGAIPQxDEbT6IoSJ5cS6TfQiBABkxGi3QFYRxCpG5uNcNI1UjL5Dpr5WNNkKkpJ0axPlCYcjYkFjZlBHAK7mwg3L4ONwV9tDvDZRx5Fu9fDD7//HyPwfUhSU8HPRpSUWXyqbCqhmlIOyrlKXKtIOJ+2oDqtUhECUF25yhQGN91uRywv9w7VhfNWATp69CgDQMt1jggSYGOIin5Ago470sGlS5dw7snHEXKIG267Ga1eB2N/iI3BZURRNG3GSW94LlpKygoi38doNIR/8SJam1sgR0AmZSK5RaV4o1ESmaVPTH9PzRjl0dYklcLZeJuBTD8RwIAOA3hS4fKLF7HiOHjsjz6P733f30On24NUKnHUBSjx7biQW0mFaya09kxbPk3D5TQHW9IRtpqUmrpoe6hMeYvK9vITZg3HcdBut+5IZGIhJ9oAgJLyIGdDZJ6ZEBIEQQJPPPlNPPfyczh4+Cb0VpYwHO3g0pXzScQlIIXEDLlO8dFsoddMixAIGPvQ4zGgFaDENO80dSlo2n0wE5x056fClF2szPtnof1M2JB2MyR3jaSCIYl9R96Ed77pHvT6PXzpy19Cb2kJjuNACAFHOXBdF57rwfM8uF7y03HguA6UciClhBACJMtp81xpSxaSKGTc2dqMkC8B4KYF4+mn0lxalW9PmUBBEFqed9tCydTUWfrABz7gSakOa62RBZJif0eADeOrX/sKtiY7uP1N9yDQE1zZeBVEBCnUzD+pUZPxQs3MjDEG7Afx5yINwwwiLkP4yQ3PtLJMBYcSXCkVNkp+5+RvOW1VMDspvqQB3HDHrXjTffdi9eDBOIpzHURGIwxDRGGIsfYxGI6gdyKw5viZmAxBAlIpuMqB63rwXBdu+vQ8uI4Lx3XgKAWpJKQQICEKJRoznGtaJswATzGDxZvWphuGK/rKpreGYjhba0gpb6sjC6j0gY4ePXpAKnkwiqJZDYYxifBo/PlXv4xIMG67505s7W5AhxGkkBnBYdTnpzlnq9NiKPIjkDFgMUsN2FFKsvSHFTRNcfVymogSEgPK1/8wgx0Pm9ubCF58HoGZoL9/DV63C8dzodoKXteBEDGsICiFA2iKZUWRho4iREGIcRhidzBCFIUwUYymMzMECFIqKCnhKAeOoxIh86aazXO9jKDFUAcJyjlL0+x6Nk1h69meqSBQxiCyPfMds34YAynk/nidRGMBIgC81uutKKnaRpt4vad6lfGlr3wZkdK48ZabsLF5CUQEkQhPGc/n+q6oTK7JRAbCD2dayZicv0RUjWrnJIybFGfFX6YLwkXMiJQHlhLKURBKASAYYxCGIRCFs+rHrFObajUhYijDkXA9hZbwICh+jSCmqRM2DB3FUWgYxvjYeDJEtLsFHWmwNlONKhKt7jgKrhNrMs/z0EoEzXFdOE5sOpUTC2WKcRljMveFpvcna72rauGiKIIQYvXIkSPuuXPnAlsoX6mBRqMRiWzRPzOUUviLv/gKRuzj8OHD2Ny6DCFkTZUN13ehFsPyKAJN/KmJ4URoiSl2nEs4S9F7pJrWYS60EnG+ZikxiwIEnWg0IVLfCpmfVIq2cldpDCJtECEsmIUZIk+gWKCEgFCJsAkXQqQaTSDds8YYmChClMIdYYixvws92Eq0dhxVpsCsoyRabgv9fh+ra2tYWlqG63kwbKC1zq8A11eham1A4O773ve+9rlz54JGGiitASFPrjmOAzbGGIZwXRfPfusZXNrdxK333orN7Y3YZDFbu4C5ptavJESp6g3CRIAyNzVx+ignMDRFjHkaYFF1JwTXRTOcoeWIBSQUApxqjGkejsrNerXKbapvkg1RiFKYgShCxJzJ4PPUxKQaLdVeQkqoVNBITE0oOG4aZB0LSBSEmEzGeOnyBTz3ygtwpYP9a/tx0003Y3l1NcbetM4HGxXZsdj/Ref+O+/sANg+ceJEaZErNZAQQggRq24pJXZ3dvCtF76Nw3fegt3hAIJEUrxta+pulIKcvSfFZfwAwvcLyUxMU91cslYxnlSWiQrTBpoKYxFmI4pvBElCSARSEkLGWiJHBsGz6j5Cw5ZjypiQogYlAvFM02UhB4rTCjAmAhBlHOmc8UxciFjQVEui11vC6o37IFjAHwfY2tjAK3/5JawtreKee96I/soKwjDIXUu+UjqTA2R2fBm6jaOw48ePMwBII7aiKIIxRigp8fgT38TqDfsQcgBOJJi5aQBJ1Z01yc4zzHEEFoSzmvCKWvWc+5wuAnODfuC8IHJRMyZYQSgEhKPivJvIVgJwdWV7ZS8ZWQrvub7+ngvinQVdKVNOywXTaQyiKAL7k6S1SsBxXOy7+QD2HTqIyxdexRe+/AXcdcsduOPON4CkgtZRrtw4e8dMnEZyVtqr7cb1QKkJY8WSDUMpxS+99CKGwRDtpRYmkwnSvneahtPVOH2u7qZUTkl5p9cPwEESxqepCS632xhTiDrMnAqrqbDk6/WKwCgzYECIBMU4TprdL5ogWjDnTcW63BoSLCo/qWZTzJqaUuQiMXvJPfIDH1e2r2B7tIm1Q/tw+5vuxksbF/CnX/wCtje3IKVTrpw0DGaQMQwhiByXXAA4ceJE84IyV3h9pRTCMORnnnsG/f19jCaj6YkVtYqtfIkyzqkVrsjcPMMMHk8AHRYwkFmIn60BYpPvkbJX3c0y7WAuVExyBjXOVh4CEQFSSQglE3ymGnnjrDAi72jP5WzJClEWvioVujbrwM7BtTzDpWTiK23tbGFnvI2b77oNvRtW8eWvfQkvvfA8pJSWtM+UkAEkhGqsgdIy1sAE7VbLw6uvXuAAEdy2Cx1FliremsQd0dw2l2lxmDHAeBJjQAmbBBuetVTmao04Z/7yDX8zCIDNTAAx1Wpmls4wM0GcFqcB0ElFgUhNmKByPa2l1acUSVAzhdVUWNjadEs5weOK7gQGT4Oey5sX4XYc3HrvnTj37BN4+sknZgFRfk051r6uylqnWh/okUceSS+75zgK5y++it5qH1EUVbQhcwXCQ2iEIyYRiTEGYhwAxoBFAuhl0eLsPud8E0sxV5ar45qyVJQ1RwZ1jZP+zNAMGCliDZR1oottPHMw4OvVSU2W5HvmQmsr7lMoRAqFneEuPMfFHW+6C9/65jNgZtx9zxvj3CWly5IAwkIvXlDmCEeMR2OM/BGW9y0jigIIiMI+4IqLW6DiLtUM2oAnk1gTsQBn+5643l/lyvIkqhBvLvX6cVISEjJDy0R4pJjl0ipYO8navXp9alyprHhK4TfV4P/ZqFYKgSAMofUO7nzjG/DtJ56B12rhttvuQBiFuXrxKhTaKkBHj15iAGi77mRj4wrgCqTt75Vp3FpKy/o64tT9MDoCxn5SbpGNMgoIIjerCCULGlU2PIX3MBCCACWnYTEJmuVaKzgNiSzmLNvBehXki81SpWTtgrSVfGTBW5HUnu+OdnHb3XfgqaeexlJ/GcurK4m7wiwEkTG8vEAUFv9cXu1vbW1uwGk7ZLRpeBHUsKSznDTkMAKP/diZnnZ4IOPXlLsxrMQDhVogFAkRjM3J5mk5ayQESMXAXayBRI36m0kyVbZA0DzyoZrnNahfpBqRS+qytA7hax8Hb7kRjz/5OKIgiBFwY1LUXCzc1hMNfRpNxnBcFeMBRPOizXpepao+5PSGBiEwmeQy0Mg4xMZYHOVSxIWMAMYCZ7KMGSYf1eWEh03sA0kRF6vl/J86ASi8NocAZDHLZl9lsq441RSX1WTnkxTIZDKG03EBl/D0009BSZHgcwbGmMnCArS5s2NCE0FIATbmKsgU62vLpyDixAcmfhKCmlxRVpl2xZSoTopNgLO6MZ5RoNg0k8lrL61kUngfm7Fr0kBRWpOkKm4PJB5U4zzkk3b2zU22TZ34RIPhLlZvXMPLl85jZ3MLUhDFOG2kFxagjYsXBRRBCMphJ2mcyPOEhC0NSTYpTG6gGQfgMMoJ1vQmWzs4s383Jfwj23SYa/rLhqpmhgXF6LKAUUkWXopM/dC8xBdhcd68THklI/MT9r7jIgbP5Z68op6y5x1romIGIq3R3beEZ194Dkqq+N4IN1w4ChtMJuiqpZqlyZdhzkm8V9CKJjkwNuCxD4rCFAoFCi3UKSjJtlCVCbCQSEwjJEKB1YOtYTYTwSgJqSRIFkHE+Q4G5bKAnI175jCPUSU7EKFAqGRljKEyfQznqPUbxYiCCL4/QX+lj0svXMRwMIxrkHR1GF+pgUIOWSiRp3CpBDeocStvSc5MkpoYjYGkB8zGxlX17xnSjFLj+fQzJlM6mmVOy5kyE4OIjkr62bKZ+CbXatEuU8GhBp10TdxHnlNsQI1b0OrOysDA67Vx/tVXIYgwHo2xgADFYdju7m6YmAWqQlgXgVHZdsE8qwXCcJJ0SBRqhmEnIigyBBSd63IOLYNAZ9IYWTRcg2CkhJRJFEa0kInaywSNppxsXMrm2T2G3N958Z4hQYQoDNBa6uDS1gZ0GEIIWkQDxakMKdmVcQ8X15GKFrkI6kFnCz+iSarmxuNZBSLyjq+N+CDPvVhE7228idncW+FvyTOCAEsxK4gXVGnB6Cpbjfk6T/CihjrH9qoxBkoRQtJmMplgeXVtdU8+UNpBkauhbWCb2QZisa33iKfNhWY0hmADgsiDloUiIKaM3c90EZTpZDDVLIJmPgab2U7LlXUwEBLAKgnfZaYOiGxQ0FVQ6i9MOL3ocIbGtBB5crVMuSsbA+EK2trZRqfdHu0hlSHSgrdyKMtlIeFFuy155tCaMAKNxjPHOsfEyda1nCp0pvwoKJoJDRGgmaCTPJckgiKCSeK2Yv9VJASg1LTcNE6iNqvj4AVNBZWEsI6nmCxoP1cyobAVA7f0YRPleRNp5nxrreG0HRrsDOFJZ7ywAC0tLbelErkRDHW4BRWjiUZ+deK3+AEwmQDCHmVRWjBGeWnN/58AGKgk9N7VjCuascHAJMnoewTskwI3SEJXADpNkyRCqKWEdDLNgyQylYLXTniKbPJcEiLKFiZWzr6iChGi2rEuXLIc+XxjkuBhA8eR8PUYwXgPyVRSqlB5XdAGXJ0npqYWPvVp/QDwg5w5mopFprgeXFAIaSFa8h4pBHYj4GUGNpWE8RRIKaRjpibMeElHOB9EOKA17hKxwIVpV6qUEK5K6oAogQ1sQxnomlK414b4VM6dcUkv8WJYlI3socjAZeL+vxAag83LiwtQPPTVzlDLFrZ5zrd5FTooYG3nmaLAfpC0y2Tq6YuLlym9KGqENKfzUmDwPEmofgudbhtuy4u5g6SYCpkOQoS+j43JBMFwgrvDADLmFYFJtI9QtjqgupkZdBUkCbRAKpUrKD8XLR4hC999XpBSd4CUwPZwyAsLULYd3t51QYX+LLLX83K1/U/TGGY0AarR8vzsq0wve7ofFQk8HwIvuC66S110+l20lnpo9bpwWh6kE2shozVCP0A4mSAcjjAcDPH0lW3cvTuA4yiw58baRybPbC+/7UbTd4d9jObM7tmLqFKhQpwojm4dV0EYubgAqVLpBC++XjyXgzruVxpNIMIIJNN+MDMdV5TPFVJGjmJn2CHCJhPOd1pYWe6hvdRDZ2UJneVltJd607ZkEhR3jQYBwrGP0c4unI1N7HouLr+ocdgwqO3B8ZypBpoO/IBtYAvtMXCnhnqBG89Bs5eV7D1hmS2gE1LA1/7iJmwe+R0tLDFFp42npazamClNb568nHO1LtnoLK5nAXwmvOC10V9bRne5j87qMrqrK+isLqHV78JptSATPyiFDILxGE7bg1ISstOCNozxi6+CWh4cz5u+P+2CuBZapJqAkxfGhrLkC7mxTlw1Hy3bUseLTeMkYGdnJwcyNxKTpJ7IYud5wbkD1dgGAzELWb8Ndl1Aj7PBQF4xJyuWshwaAA4IL7otYG0J/bUVdPetore2gu7aMlpLPbitFpTrQCoVs5YBMJGG43lQTvy6ch1MAOy8cBHCVVCeG0diBbKDeu3DFchvNaza2O21+btUGJ01F47KV+GxjXBhymif/5wQAu12W+xJz3C5+PbqJtBSgXGdCGQYcnUZ/sF96L/8MkIxUz659uGEvIBB0GBIBl4mhd2lPpZXltBdW0V//z709q+gvdSH2/agXCeJqORUvwslk4KxhBEjKR3x770D3mof0nEgpCphQPlO6qbjqepHiXGVCWO+hvA1W0N7tswbK8eDxEIQCSlbsyzF6Ws/tXmeQFGx7iBNoCdkBK5SGLzhFgQXLkKZEFHCm5jdISklsDYMBcKWAS6vdNFf7qKzvIzevhX09q2gs7wEr9OB9OKICoUR4yQJkpwpYYKO+mA2cN9yd9zZmQhdXMdLKFIk5zL8DW4y1wx25etZRV2QECa2txPZhhBRlrebE5Kwazb2m7C3zIxl8JoQEEpBCgG10scrh2/Ajc++CEfFBAfSMqnGFYQdzXil20N7tY/2cj92mleWYrPVaUO6TszESja1HeMgQkk4ngfT7QJCIPJ9CCljn6lowthiUiu4HRaAwCqH6RIa9vhYNiaqMvM8Z1Yf2Rt5511QpQBprXP4NlW6/FTrEzHl+5Wy7d9CxERMstWC6zhQh2/A836AA69exhp0LoeVAvObIDzf78NZSQVnGZ2VmHHVTW4+SVGY1mrHEqSj4LbbICGgXQ9EgHRdKMdNwMcMMTk3sCI8j9y7cOMqqvQZdhyNa0dUFzOVJleZaGcro6l3wlkGkUJHjFJ7HPc0paObx0Nf9JOouEstQ+gonpgnHQeO58Ht99AdDBEdvgGveArbVzbRnwSA1nG+TEgMXAe73S7cpR66S310962iu7aC9mofXqJ5KDFbXGTest3C5PgggnJ0/FLS0hyH8Gyf1VUz4yvvc1BlGFVCabnMZ0KcH1QsMhR+RMiz92d4K9PXmRnamPLsEqJcEnkKkXCBK2Mq4OrqTBiVWlVmJ5JjoCj1u9TszERvxqbEhdfvou2vwDBDSoFBu43t3QHCsR+32DoKbstDt9NCq99DZ20FvbVVdNaW4XW7UC0v9l2IKsquLIg+CJACkhSg5MyRzNYBsSWGKAxntJV4sU2suMyMP11ZITI8j5m0RUpGpTUirRFFEcIwQhgGCIIQQRDE/V1RXEslBOA4Cq2Wh263i263C8/zpj4fs7Gm45lm3JXZpk3e68C5aIoMZ5JQzBZzb4fSGfnygNLOSpWAlFCeh3avF9OrpH6RcjDxXER+GJcWCBELWq+D9tISOmvL6Kwso9XvwW0npkuUdT5bFCUVokyaNr7lOxzYOlqS81hWUa/lOT4Tsqg8rd4MRGUYEwtFFEWJQPixUASxgIRhBB1pGJ2SuQhIoSClgud6cN02llsrMdN/AsIGQYDh1gAXz78MzSE6XQ8HDu7H/n37oJQLrXU8XyTPJjPlkZymh5jnopjVPhCiaXP+DN6eDbJn2/xQ2LPpXOcfCIJyFQidmJQpY9a8XhehH0wFSLkuvF4X7eUeWv0+Wr0O3HYbys1EXPZByZVTCLmCMc2WL6KMcAnQNNTP5u1S9pBYMGJSziAMEfixUPh+TKgeRjER+qwcRUxHP7iOC9frodtLGGAdD67rwXGcGU9i4h8ao6GNTkyVSUhOJRypQBAIfB8bm1dw4ZXzePGF8zh4wxoOHToEpVTCWEZ5zleGZXbZHqIwCdWAYJ0q6oFy8WOJHKF0c4SEdAle1i9qeWhNJtBBBDY6eY8Dt9WC1+3Aa7fhtFxIxykwnHK2W6XCCc0XulOWg6dAI5yalRQx1zrVGCGCMEIYJAKSMO2HoY53uE6ZxuIKRylUTA/s9NDrefC81pRIUzkOZIJLMU17sRDpKBbCKMQgGCIaRdA6FhiTluhaYKl44xOkUui0Wljdvw833Xwzdnd28a3nnsHLrzyG228/jBtvuCHptyuG8M0b2apzYUo2HxxkA0aYrLFueRZyHFanguORiKOjVgtRGMaspibeWULJBD12Z3hNxmGurIJJBCHPbxifn0l9DBMzqwbhjPQyNSNBGCAKI0SRiScKcaIxRKwtHMdFy+uhn2gM1/Xguk6iMWLTmjY7xr5MlAhHhF1/gGgYzbSIMTH9HefZ76ctRkl5iRSq4BrYp8mPxmMMhkOQICz1+njz/W/BxsYmnnjqcWxsbOHee94AKZxYGxKmWiwPnKo9+kDzB/NU9IdxBZNqTUcCxeZMOBKOFFCOA9fM2plTcyfkjDMwbbvJ+hmziCSutdZGIwo1oigVinDqfPp+GJNXahP7GJyQo0sJpRy4jgfX7aLXW4uJxN2Y4zklEk99LmYDzSZmXE0EYzAZIhrEGsMYHe/0DLHnTJgpQ9RFICHzheqWPcuoIfUq3BNBMZ0wg7G9s4PtnW2sraziB975g3jyqafw9a8/gfuO3AvP9RDqKMPKkZHhvYbxlcWzbJMVtr5Wdmq5EqhKQ1WozGCTDDsYY1ZDpI1B5AcIEz8jjCKEoZ45oIlwpCpakIx9A8eF63jw3D76S60p47zruokpkVOIi2EQ6dgkhVGISEfYnQxioTPx9MSsKclyFlJu8B3V5NZmoy7ndmjwvNiS7eQnqVsi4zXd2NrC7mCAe++9F+fPX4iF6L670Wp7iFICzoat2DUCFOW1B9tr47mm+KfI4DqNSrIs8xn6f5P6GHrmgNqc0CAIoCOTON0SjoqFouW14LmxKXHW3KlQqISkW1DsY6THSs1IGIWYjHehhxEibWYaIxfyznykGeULxRCAtSaH82O68+UEc/Cla53eyEelUkpoY/DcSy/g0MEbIMRd+NrXvok3P3APWi0PxjBEw6OrptVrzBX0+AUnOVXRseqMd7NhAx1pBGFyw6b+xUxbBEGIKNJJbpNAJKFkzN7uOC48t4du34O3LzYhjuPOohISQNb5NDNHdzzxMxpDJ1hI2b/ImRMQpCBw1piwrSOXYTKk3XXcnmW+4TLYSgX33qDcaMqlLlOaW05GuU6NGbovhcTLF87j4IEDuOnGW/GNrz+Jt37P/dORXE1qkWpSGXkOQ/uA+GwpQ2zXpYw1zMSfYGtrC9tbO5iMg2nIGuMYElLKxMfoo9dvTWn+HcfJh6tA7F8YDZ1qDB1i4g+mUYnR2agkaz5mJiUNxEXqfFJVmQU3WLh6mKJRz+mckU7WjnFerKvVOoWnQNCplMLFS5dw4OB+DIcDPPP0t3H//W9KEqi09yiseLAqCtrUMZQJkrq9s40L51/FztYArmphZXkNBw+toNPtwFFOUkZBs2z41JSECHWE8WQSO58mijlqUo7DQv3KdFZY4kQrISyuJdvS4fYbfhX2ollBabOyM/rO1Mnm3AwpJS5vXMFtt9+OJ584h0sXr+Dggf2IkllqNTDQHBPGFTmcjN+SjIXC9s42XnzhFYQTg4P7D+Gut9wHr+Uh0DFz+sAfIRwG0NEM9JoybeRmYWTmTpCAJMKUGLamso+beZmNnQ17FoxKmDvh2vWZfqeFp3jsneEu7rjjLjz3/DNYXV2O4Qdj9ggkSpv6y0uuEIRQR3j6qW9h8/Iu7rjlLtx85BaEJsTWzhaGG6Mprb7I0fcTQKqhaWjYPc5lFvtsG0ztzeG6Mdj1BuO1PT63+UMIgSAI0W630ess4YUXXsadd90Kn02dAmrgRDOXGE4NM5SSGAwGePzxJ9Fvr+Cdb/9BRBzhxYsvIQwCCJHwDCYMH5zl/altWyHrYLV6bkGq0E68kK/wXX3wtevyoCq6mJrZv3FfHWF3dxcr+/bj2WeewqGbD1YwtDUqqlfW/DKbeEbqxtY2nvrmt3DHrffg4A034MLlVzGejKGkgpROhmGMy5mMLBpNXDtz3l7Lcz31AF//fp1FmMloceoPrix/QPX4hZTw3RgwMdqtDl49fwmHb7phj6mMHG6YMGLEow9waWMD33ryedz/pgegWi6ef+UFEBEc5WQYw+o4eJOgtYJ+0O78Vjf30pwuh6Z0lZxJnhFdp8YvzjrLDcaB8xz1MacSkqsK+6lCl5OAH/hY3b8fly9dwE2HDqKlrqIeKGW4MGwgBOHK5hU8+fizeOAtb4Mh4Pyr52MqNBRpVKocX65gaFhAoeQIFqyBlgVAZysqUg2CzjLsVJNV5qK5pSoWN17Ym6IaX6yokHmRMLKOA54AHWm0Wi1I4WA0msDr9vaSC4umgmo4nvwyCXw88Y1ncc/d9yFijc3NTThK5XZudW7Mzpg8Dw+ZAZWFIW+8QIU2V6MitVYrN6iFGtDuc70082Ll5dzAd7FeSxNmqzm5SW0M2p0uBoMxWj1vbzXRnImASEo8+dgzuOnQrXDaDjY3N6GUigfjWovEufrG0Zw9xnMis2vhq3BzB7O6MLlhezua93w1/szc92dKKalB22O2fDahd/HaHkaDHThS7lGAEtjfcRw8/8JLcKiNfQf348qVy1BKTQE+rgEg2VYjzHtk9WIbAsN76CqZn7SspkznSvIMLo0aWKBVg5ufYb70lGpWgSvtVMqjVDUmgo2B47gIA40gGO/FB5IwbOAQYTga4dIrV3DXPW/E1vYWhJQwZv42yeViKV/IxfM0bJHKZc68i0bKiIvRHVVGX0xNtCKV6qXZPlN7MdPF9T0MXIQnapksqLoCoEr7JwV0yQxzDMaDxTtTXdebrulz33oBa/sOIIgCGK0T+n9GTc9cfSkCNSMOYF5Ad3CewYvnuZVsi0a44vss8pc62FxHR8cV7TQogJwWejqLXFC+E76ZvuIFR8Fk5tMaNqyUA2hqL0zzm3YKbG1vYmdziP7KMkbDYW48Yo5Zl1HBIVrhJXNz1olKJVB4coH5tPb9NfTDWZ7PEiGsxTpwYfRc/vcqZtUy9eiM0H0W/drG2+VPxKDEcso8v73aujD5dYRhIhK4fPnyGABOn16AXAE6ghASLz1/Af3lFYRRmDCF0dxUIqFI5s21s2sqKtvt42bYMuu0UlVjPnkjLejhEu+RH8DOWFjRHI/5HHdsYRxjywzkrJYjC7tboQW90NZMQmAwGJiFNVC300GoIwx2xlhaXcbEn8RZdGbrzSHUwztcIIXKqyG2e5Il08AVwlOj/azzShIKNWpkDzO0aXwVzFJUQelfuPbkvJgKQkfNBpBQgRGeS5zUhXWpoWNmpNN89oBEux032N7ehdfqkFACPDFJ4ZalRqgYcXEFGRtZGMxKX2IK02e4WaRP1SM4qTICttMbsPUecek4tpEJeZ1BlbgRWxvluDiVYRZ48CIEvwuUwlKFA5/R9nsiV3Dajtnc2kWn1437h9I+9QYzMaqQG2LU99EXPkeMBVMEdnYCtqSBypERN8ChqKLvNEd9nSNzqo8ELUP0uA4stFwslSeMW7ohqzma2DL2lTNdGXttLNzYuGgmvsDywWVoo0G29q4FOTvm1dAsgseVJtHntn4NCbh12D3NBTDLrGlVRE57r1euXQHrnaYKJtfiaPDm8H/sQ2V8qr0K0KVLG9zurkFKgTDUFc3LVPBuGnYK1OAv8zja7T5VUe9zJSdzVfKsKFc2CJCY6/kL2TKTqzaw57nnV1mCzxbeJZ75D7zXsoApYwdn/KZo8WErOxu7FHdKZsZPZuPbhlnP+Z0h1Hw4iy1zT80WaOo+1jiPPOe4iwwf5CZDG+d89zxvgYszS1BgJZyLYdiar7jQ3Vt/9yqHrURQbeU5YDZcDLHsp8PVtcdWp3reraiK1Ba4KzYamsZCwIsNdYedPpobi8zeOO3mj+y1mTIube6yAue9tfWkYNFwMCCpVCb6KKpGbugM10U+9XmbiprDBSdENxnzXHPGC38mk+bgRYjAeRHEqP7YVUUBVKd/Cu7IFEA1iPZSVO/7mQ7FHEkOl+B8LsJUPAfPK+JyVHHRpZuBHOuZNQzPTgsvpiymi0igubXWXMAn7f1xRIUyOYal/59LmolstLwMlLvEqMSyU1xPwhwirWrCRvvvGVjB7NWJZmbKlWXYJvKwzaWdV/ySZ2wq0cFYh9YUw162mERTECQq1BVZFB0XmNOo3DnKTJXzAVP22Owm4sKoy6oWca4DZ3J5unyUZqPF49qkP9vIyeox98wUbOZ6jrvKv4wnu77WGjAp/zcvFpKWGOJ4joqq+BquUW1cE/rMM5dVnXtU3ddvn2tiu3vljt3G4T7XKRGuzvI37Giyw0IZP4myrUtMURRhvLszWViANjd3wzAMSw1vXBH6lbwhLs/jIrvFmQ/+F9NiXM3eXsZFrh6iqRxSSnU0q9xs0gHPXwtqULLCwN4r12qWKowi+H5gFhagdrvPYRgWTBjP6c0sso3aJhhTbbF9FV7EDTcvzXXE57i0C5aQ1E1n4jnBHTeeKTLbjNSIUZgXTeNW7ETAD3zAUXrxmmg9GY3HEzAzFYuWeE43EpWqB2vaeKrg+T2pDaqtzONcnUBTqI0azABhS5zIC04V4Tlj6fLONS9kEStG5VDFmc7692g0GGGwORgBwJEjR3iuAKVv8gN/dzgasWEmTjnT5hTocO4mViDVFnPEVcnwOS3HtLBvwdXVYvPUGc+rlebKmkFC1RAUblBcWQy3uAEAwE1ad0sMtJxvSmRjDI3H44B5PFy8oCzA9mg0nJi6XP5CGHK59Iq5eph1sWyTc+B65nuyY8JtRWYZ4Dz3aUZh9jzyc+SRfz3/74yI5EbVMyzDymevcbF6LF/JwEB+fea1K5XK1pr2RNV/5zQLrzV83x8Z4w4B4OSJk/M10MmTJ5MpkrQ9Ho+3wihqO1JZmByb9pDs3XNl5gXbObkhpls/RaeRJ83F4ZPzEw9soVHgOce66nkaXDcVkwtjm3MOCYdhSP5ksnXw0qWdqlssqlby85///DAIokuTiQ8iym236Y6sLOlETsvAMqP9bw4twV58Na7QHnPKVSwatqjN8mW4eU1f/q+oI7P3DDyZTBAEwYXT584FzGyVX6sJO378uEwE7tnRaARjzOzeU5OdzPaZH3OTn82n6jVr8Frkdl8roS7SOfE1FNKCC2Cpw67Nry1wiYaZx+MRwPwtADh64qhs7AMdOXIkAXbEX41GI0SR5rLp4vlnVVFlylSdg54uRCa9nPNRckxiBb+hypepK3PPEEBkGwPY4tXkHOapRi2LC2dnX2QK5ZH10ywLVRKPjNbmayTixbXNaa8pys8IdYThaAgmfhwAjuJo8zD+3H3n0nTSXwwGQ4wnE1KqO6cZkhtPD5v5D9RoH1chqdyg1KHKZ6wKg5nneVdc0URZj66zlbG2uW6sL9BP4qcM4s81VC9cB/0nP8djnwaDAaSQXweAc+fOcXMN9HgcyrdM/7HRYBgMBkPJhrnpLqgy1fnIAQtUyFwtbMx7+M6mV7nnIosFr6sQ0WX9FZ5pDi5tggWmHybfZZh5OBzK0XDoE+jrVRjQ3EnQzIz/5Z//r4/tO7D/LYdvvtl4niOmM4WaNolz/dRsLpVncGX2npoSnheAsibt7/WwnwX/5fm1y9Qgg9EEW+a9+u1UPy2xaj0nQaRffuVlefnSpcf+46/82vfYczNzcKD19XVJRCxIft6wxnAwMuUhFAt041kql7gUOXAOt7E1IlqfcwSLi65b1WlavjePHXH+b7biOlsdnO14Nm+r4voWKoWsNAVFP6qioIyB4XDEWodwhDoDEK+vr8uFgcTU5hnd+i9REGF7d1v4QYAsM2tJ+3GVAeLMUDXO0cF8RyLsvXqfTYsG93IMvorPlgCBclnqPFCSCh1k6Un4YYTNrU3h+wEM6Hfr/J+5/m5M/bxOP/6hK1/r9jr3LfdXeP+BFSGEKBeY8LUZ3ctWt4/mTgLkykL6uvJ8LvCvsoWP9VrLMy/8/bVONPMCJElUYU6TXnjNuLK5ba5cuSjGw/HT3/zKwSNnz57UdXe3tjf+xIl1CZw0/oQ/QwJ0ZWPDjEaTwhzsoqkq6PgFfFJGIdStBMq49LTtZM4MXsl9LpMGyacS8gPhpp9DNRBn0wRlaCFznrmZIZw7pyqcx25bS7bQzhdQlaqxrN3ED3DlyhUDAqLI/KezZ09GdeargQCd0ADQxdJnRoPJVhgF8vLlLY7CaDZ8rniji3u7eKF1qv+qiL4XMCtcH4VYRyrzPES5YKp5Hr5Q/j3nBjSA2eZbSJ57+DSBGmmDjY0tDvyxHA/HkROITxdKPffAzkHED66vq49+9N9c0sb7tXanRTu7A721vQtjZoUFjEo/GUXGjKtbkPktOLyIvaSMdbyWgHETh6EqDKKKn41cKa5g8KjePzGFIWNnd4CtzQ3T6rRIkPrMJz7xiWePHz8uT548uXcBihHIeOaHq27+5YlvdrwWictXtnl3MChMDW6C7HCtOah+ll1yO9RXfHcFxQrVk07yPGIzbu4IZ/vRmOubXyvTPFQtMFflhSfnMxyNceXyFVaupMAPA0d0/jUAqsJ+kKMhm/M4e/Ysnzp1Sv7UT/zY7jvefUz0+94PTcYj7ftaeK4Dz/Pmosq4DsT8izdWN22gpqtQObR421DjY/Me5mCgohZpNhxnPJ7g4sXL8P2x7va7crgz+sjHPvLvf+f4qePy4//04+ZqVjP3vvX1dQJudzeiJ77S6+K+re2J7ne78sYb96PX7cIYU83RY6lQLL6X5gGD9J0VUfx1zv2zjfYlM6qdGYIERuMxXn31InZ2dvTSSk8OdkeP73NX3w4gSMp65h5KLHLOJ0/+o0mk3X/k+xS228TbgwFfuHAJg8EQQshrowQaQC57SaP8dSkgaQI3NelCnU3aziMt8YwTgeEoFp7NrW1utV0MB6MgGgT/4OTJk5NFVF7ju3727Fl+cH1d/Zdf+FcvveWd79rstN33Koqi0SSSE9+HlALtVivfaYfiDPXZ/PQi59PccnBauMO4siuZqlqw6LUjPDZ/u77LesrRi9lARcrVVKfDbnZ3h7h48RJ2dgfotJ2IidTG5a0f+42Pf/L/bmq6FhYgAHj+7Fmzvr6ufukXf+GLb33nu/Z3e63vFwjD8SSSo5EPZgPPc6GkrOC5mQOfVbAfETUrYUYNqRdVBDZU5yd8FzXPvEEIVuK10vrOWEeEENBaY2NjCxcvXcZkMkG344Su5zkXL1z+P3/zE5/+pfX1dfXxf/rxhWqY5aIXevbsWT5+/Lj89MMP/8HbfvC/uqfba70VHIZBEMnhcILA9+NphK4LQVSdNqPqtpjK3UbNOBCmn6OaOS10FR7h1dqjivOidLPYeB1oITLt3NRmEGE4HOHCqxdx+fIGjI7Q6Tih1247Fy9c+Y1PffST/2x9fV2dPHly0QL4xQUIAM49/jjWAfHhk//qd//g/zlzV7vt/R1CqLU2NBoHNBqNEIUBpJRwHCeeWJyiZDRPmuhvqVtMzaanzKknSIslhBBgAP7Ex5UrG3j1YuKrErPnKe222s7FC1c+9clfefjHjh8/Lj/+8Y+bvbiJdBWjEunECaKTJ2H++b/8uQ+7Hv8L1gHCUEdhaBRA8DyFfq+Lfn8JnU4LSqppj/0UvrfYOmocdnFlYcg1z15l+udpwc9S44kyNHeYA1uaElN/Jz1OpCOMRhPsDnYxGAzhByHADKmglRJSG4ntjd1f/tTHHv7J9fV10TTiwnVQ2rS+vk4nT540/+znf+Z/FEJ/rOWJfaHv60gzGQ1hmOE4Cu2Wh06njU67E/tJjgOROHVcGKU5P1xlXP3IjKZCx2Xm3SbDvLiKbbbp5JVChSdlfMjM7zMKFo2JP8FwOMZgOMB4NEGkDaQSUJKMUsSO68mdnfHuaHf8E5/6v37tU1crPNfMXiT2M/rxn/7pO1su/5Lj0H8nBSEMfWM0ONJGGM0E4njOu6Pgug48z4XruHCUglISQiZTDjPRWnrHXnOGjeobBK/VrMFZgjmZd88GRptkfHqEIAjh+z78MEQYhtA6nm9CBChFWkqCclzJkBjujv9489Wtn/jcZz7zxPFTx+Xph07raw3p7vlx/NQpefqhhzQA/O/rP/9eQdHPSCV+QAhG4PswhiNjWDAzMcd0gylpw1QFC4KgeKozTU1FRdBK1QxkjUnGK+pk9u672LVS7i8V5S82KIMzw42nQ4pNzNljzGxocbp+QhALASaCIYISUiEyhCjU3zAhf/jjH/mVzwLAg+sPqrMnz0bXIydwtZpIJM2JBgB+9l+f/GHNwT+OTPjfuK7TMjqCjiIws+bYbtFMoJh4D6dHc32l6mCYKwZZ7EmIcgPMqLGZ4rn1qnnOgPR609YEIjCRMCCABCmpHAghMRn7HIb8p2zwW0ff/v2feuihh4LYbz1B8xKk3zUByvaVnT49U4//7qMfvWd3tPVQEPnvM1o/oBzpESGeDa8NjNFgw2CCSXsLQMRN/Rayz24skZrXhcNcYM2gRcCh4nGIGgkcN+hkJc4JUqKUOdbXQoBIgIQAg+D7AQsS57TB73a9zu/+4s+ffKzqnrymBSh70keOHOFU4okIv/qpX71rY2vwPb4/fEcUhfeHJrqTjTkEcF+q2AdC4lzn4tKFZn7RHDOzN1ZqNObzoMVodi2z1diiqWITZqC1RhhGEYCLQohXBMlvSiX/bKnVe/Rnf+pnzxHRlK7t+Knj4vRDp831yuR8R3zTxLSJBKjiAhwgP/m5z+0fbl084If+Ph3q5Yi5wyZaYXCXmR2jAab6nlYSyRAlw0RCasTdKUzEmkg6AGBgBM8465JEoDBMzMQsTfL58WQ8CrU2Qgo4woF0lXSllLGVNSKeYRN/mImYiJh59h0iHhMqwCaCEBEzExFJGAgiJm0y15IxJibzj+Q7iQ0mQnIEgwkx7QKYMMnLQHR+pbVy4UMf+lCJOePB9XV1FDDX0lR9VwXIJkzpmn0nLvJv+IOOHz8ukm5ic7Vh+WtegKr6z06cOEH33XcfAcDjjz/+euVGxeO+++7j06dPI3EN/qaxVLz+eP3x+uP1x+uP1x+vP15//LV4/P/GJbwu0koTmAAAAABJRU5ErkJggg=="


// ════════════════════════════════════════════════════════════════════════════
//  WIDGET 1 — Daily phrase ("frase scelta per te")
// ════════════════════════════════════════════════════════════════════════════

private struct PhraseEntry: TimelineEntry {
    let date: Date
    let text: String
    let bookTitle: String
    let author: String
    let greeting: String
    let weatherMood: String

    static let placeholder = PhraseEntry(
        date: Date(),
        text: "Non si leggono i libri per finirli, ma per abitarli — per trovare in essi un'altra casa.",
        bookTitle: "Come un romanzo",
        author: "Daniel Pennac",
        greeting: "Buongiorno",
        weatherMood: "clear"
    )
}

private struct PhraseProvider: TimelineProvider {
    func placeholder(in context: Context) -> PhraseEntry { .placeholder }

    func getSnapshot(in context: Context, completion: @escaping (PhraseEntry) -> Void) {
        completion(entry())
    }

    func getTimeline(in context: Context, completion: @escaping (Timeline<PhraseEntry>) -> Void) {
        // The Flutter app rewrites the data roughly every 3 hours; refresh a touch
        // sooner so a freshly-picked phrase shows up without waiting a full cycle.
        let next = Calendar.current.date(byAdding: .hour, value: 2, to: Date())!
        completion(Timeline(entries: [entry()], policy: .after(next)))
    }

    private func entry() -> PhraseEntry {
        let d = sharedDefaults()
        return PhraseEntry(
            date: Date(),
            text: d?.string(forKey: "w_text") ?? PhraseEntry.placeholder.text,
            bookTitle: d?.string(forKey: "w_book") ?? PhraseEntry.placeholder.bookTitle,
            author: d?.string(forKey: "w_author") ?? PhraseEntry.placeholder.author,
            greeting: d?.string(forKey: "w_greeting") ?? greetingForNow(),
            weatherMood: d?.string(forKey: "w_weather") ?? "clear"
        )
    }
}

private func greetingForNow() -> String {
    switch Calendar.current.component(.hour, from: Date()) {
    case 5..<12:  return "Buongiorno"
    case 12..<17: return "Buon pomeriggio"
    case 17..<21: return "Buona sera"
    default:      return "Buona notte"
    }
}

private func weatherSystemImage(_ mood: String) -> String {
    switch mood {
    case "sunny":  return "sun.max"
    case "rain":   return "cloud.rain"
    case "cloudy": return "cloud"
    case "snow":   return "snowflake"
    default:       return "moon.stars"
    }
}

private func firstSentence(_ text: String, max: Int) -> String {
    guard text.count > max else { return text }
    let cut = String(text.prefix(max))
    if let dot = cut.lastIndex(of: "."),
       cut.distance(from: cut.startIndex, to: dot) > max * 6 / 10 {
        return String(text[...dot])
    }
    return cut.trimmingCharacters(in: .whitespaces) + "…"
}

private struct PhraseView: View {
    @Environment(\.widgetFamily) var family
    let entry: PhraseEntry

    private var quoteMax: Int {
        switch family {
        case .systemSmall:  return 90
        case .systemMedium: return 140
        default:            return 320
        }
    }

    private var quoteFont: Font {
        switch family {
        case .systemSmall:  return .system(size: 13, weight: .regular, design: .serif).italic()
        case .systemMedium: return .system(size: 14, weight: .regular, design: .serif).italic()
        default:            return .system(size: 17, weight: .regular, design: .serif).italic()
        }
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            HStack {
                BrandMark(label: family == .systemSmall ? nil : entry.greeting)
                Spacer()
                if family != .systemSmall {
                    Image(systemName: weatherSystemImage(entry.weatherMood))
                        .font(.system(size: 13))
                        .foregroundStyle(.secondary)
                }
            }

            Spacer(minLength: 8)

            Text(firstSentence(entry.text, max: quoteMax))
                .font(quoteFont)
                .foregroundStyle(.primary)
                .lineSpacing(family == .systemLarge ? 5 : 3)
                .minimumScaleFactor(0.85)
                .lineLimit(family == .systemSmall ? 5 : (family == .systemMedium ? 4 : 9))
                .fixedSize(horizontal: false, vertical: true)

            Spacer(minLength: 8)

            if family == .systemLarge {
                HStack(spacing: 10) {
                    RoundedRectangle(cornerRadius: 2)
                        .fill(Color.mAccent)
                        .frame(width: 3, height: 30)
                    VStack(alignment: .leading, spacing: 2) {
                        Text(entry.bookTitle)
                            .font(.system(size: 13, weight: .semibold, design: .serif))
                            .foregroundStyle(.primary)
                            .lineLimit(1)
                        Text(entry.author)
                            .font(.system(size: 10, weight: .medium))
                            .foregroundStyle(.secondary)
                            .lineLimit(1)
                    }
                    Spacer()
                }
            } else {
                Text(entry.bookTitle.uppercased())
                    .font(.system(size: 9, weight: .semibold))
                    .foregroundStyle(.secondary)
                    .lineLimit(1)
            }
        }
        .padding(family == .systemSmall ? 13 : 15)
    }
}

struct MarginaliaPhraseWidget: Widget {
    let kind = "MarginaliaWidget" // keep stable: matches w_* keys written by Dart

    var body: some WidgetConfiguration {
        StaticConfiguration(kind: kind, provider: PhraseProvider()) { entry in
            PhraseView(entry: entry)
                .containerBackground(for: .widget) {
                    ZStack {
                        Rectangle().fill(.ultraThinMaterial)
                        GlassTint()
                    }
                }
        }
        .configurationDisplayName("Frase del momento")
        .description("La frase scelta per te, aggiornata durante il giorno.")
        .supportedFamilies([.systemSmall, .systemMedium, .systemLarge])
    }
}

// ════════════════════════════════════════════════════════════════════════════
//  WIDGET 2 — Reading stats
// ════════════════════════════════════════════════════════════════════════════

private struct StatsEntry: TimelineEntry {
    let date: Date
    let streak: Int
    let monthMinutes: Int
    let yearBooks: Int
    let yearGoal: Int

    static let placeholder = StatsEntry(
        date: Date(), streak: 7, monthMinutes: 240, yearBooks: 12, yearGoal: 30
    )
}

private struct StatsProvider: TimelineProvider {
    func placeholder(in context: Context) -> StatsEntry { .placeholder }

    func getSnapshot(in context: Context, completion: @escaping (StatsEntry) -> Void) {
        completion(entry())
    }

    func getTimeline(in context: Context, completion: @escaping (Timeline<StatsEntry>) -> Void) {
        // Stats roll over at midnight; refresh at the next local midnight + a small
        // 2h fallback so the streak stays fresh even if the app isn't opened.
        let cal = Calendar.current
        let nextMidnight = cal.nextDate(after: Date(), matching: DateComponents(hour: 0, minute: 5),
                                        matchingPolicy: .nextTime) ?? cal.date(byAdding: .hour, value: 2, to: Date())!
        completion(Timeline(entries: [entry()], policy: .after(nextMidnight)))
    }

    private func entry() -> StatsEntry {
        let d = sharedDefaults()
        // home_widget stores numbers; read defensively (they may be Int or String).
        func intVal(_ key: String) -> Int {
            if let o = d?.object(forKey: key) {
                if let i = o as? Int { return i }
                if let n = o as? NSNumber { return n.intValue }
                if let s = o as? String, let i = Int(s) { return i }
            }
            return 0
        }
        return StatsEntry(
            date: Date(),
            streak: intVal("w_streak"),
            monthMinutes: intVal("w_month_min"),
            yearBooks: intVal("w_year_books"),
            yearGoal: intVal("w_year_goal")
        )
    }
}

private struct StatTile: View {
    let value: String
    let label: String
    var accent: Bool = false

    var body: some View {
        VStack(alignment: .leading, spacing: 1) {
            Text(value)
                .font(.system(size: 24, weight: .bold, design: .rounded))
                .foregroundStyle(accent ? Color.mPrimary : Color.primary)
                .minimumScaleFactor(0.6)
                .lineLimit(1)
            Text(label.uppercased())
                .font(.system(size: 8.5, weight: .semibold))
                .foregroundStyle(.secondary)
                .lineLimit(1)
        }
    }
}

private struct StatsView: View {
    @Environment(\.widgetFamily) var family
    let entry: StatsEntry

    private func minutesLabel(_ m: Int) -> String {
        if m < 60 { return "\(m) min" }
        let h = m / 60, r = m % 60
        return r == 0 ? "\(h)h" : "\(h)h \(r)m"
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            BrandMark(label: family == .systemSmall ? nil : "La tua lettura")
            Spacer(minLength: 10)

            if family == .systemSmall {
                StatTile(value: "\(entry.streak)", label: "giorni di fila", accent: true)
                Spacer(minLength: 8)
                Text(minutesLabel(entry.monthMinutes) + " questo mese")
                    .font(.system(size: 10, weight: .medium))
                    .foregroundStyle(.secondary)
                    .lineLimit(1)
            } else {
                HStack(alignment: .top, spacing: 14) {
                    StatTile(value: "\(entry.streak)", label: "giorni di fila", accent: true)
                    StatTile(value: minutesLabel(entry.monthMinutes), label: "questo mese")
                    if entry.yearGoal > 0 {
                        StatTile(value: "\(entry.yearBooks)/\(entry.yearGoal)", label: "libri / obiettivo")
                    } else {
                        StatTile(value: "\(entry.yearBooks)", label: "libri quest'anno")
                    }
                }
                if entry.yearGoal > 0 {
                    Spacer(minLength: 10)
                    GoalBar(progress: min(1, Double(entry.yearBooks) / Double(max(1, entry.yearGoal))))
                }
            }
        }
        .padding(15)
    }
}

private struct GoalBar: View {
    let progress: Double
    var body: some View {
        GeometryReader { geo in
            ZStack(alignment: .leading) {
                Capsule().fill(Color.mMuted.opacity(0.25))
                Capsule().fill(Color.mPrimary)
                    .frame(width: max(4, geo.size.width * progress))
            }
        }
        .frame(height: 6)
    }
}

struct MarginaliaStatsWidget: Widget {
    let kind = "MarginaliaStats"

    var body: some WidgetConfiguration {
        StaticConfiguration(kind: kind, provider: StatsProvider()) { entry in
            StatsView(entry: entry)
                .containerBackground(for: .widget) {
                    ZStack {
                        Rectangle().fill(.ultraThinMaterial)
                        GlassTint()
                    }
                }
        }
        .configurationDisplayName("Statistiche di lettura")
        .description("Streak, minuti del mese e libri dell'anno.")
        .supportedFamilies([.systemSmall, .systemMedium])
    }
}

// ════════════════════════════════════════════════════════════════════════════
//  Bundle entry point
// ════════════════════════════════════════════════════════════════════════════

@main
struct MarginaliaWidgetBundle: WidgetBundle {
    var body: some Widget {
        MarginaliaPhraseWidget()
        MarginaliaStatsWidget()
    }
}
