// MarginaliaWidgets.swift
// WidgetKit extension for Marginalia — iOS 17+
//
// Two home-screen widgets, both reading data the Flutter app writes into the
// shared App Group "group.marginalia.widget" (via the home_widget package):
//
//   1. MarginaliaPhraseWidget  — the "frase scelta per te" (daily highlight)
//   2. MarginaliaStatsWidget    — reading stats (streak, minutes, books)
//
// Styling: a translucent "liquid glass" look built on .ultraThinMaterial over a
// soft matcha gradient, with .containerBackground(for: .widget) so it composites
// correctly on the home screen and adapts to the iOS 18 tinted/clear modes.
// System serif is used for the quote (no bundled fonts required).
//
// The Xcode target that builds this file is injected at CI time by
// ios/scripts/add_widgets_extension.rb (the iOS project is regenerated by
// `flutter create` on every Codemagic build, so the target can't be committed).

import WidgetKit
import SwiftUI

// ─── Shared App Group ──────────────────────────────────────────────────────────

private let kAppGroup = "group.marginalia.widget"

private func sharedDefaults() -> UserDefaults? {
    UserDefaults(suiteName: kAppGroup)
}

// ─── Brand palette ───────────────────────────────────────────────────────────

private extension Color {
    static let mInk     = Color(red: 0.106, green: 0.149, blue: 0.106) // #1B261B
    static let mPaper   = Color(red: 0.980, green: 0.980, blue: 0.969) // #FAFAF7
    static let mPrimary = Color(red: 0.227, green: 0.400, blue: 0.141) // #3A6624 matcha
    static let mAccent  = Color(red: 0.290, green: 0.478, blue: 0.204) // #4A7A35
    static let mMuted   = Color(red: 0.435, green: 0.459, blue: 0.431) // #6F756E
}

// A soft brand gradient that sits *under* the frosted material to give the glass
// a faint colored tint without becoming opaque.
private struct GlassTint: View {
    var body: some View {
        LinearGradient(
            colors: [
                Color.mPrimary.opacity(0.22),
                Color.mAccent.opacity(0.10),
                Color.mPaper.opacity(0.04),
            ],
            startPoint: .topLeading,
            endPoint: .bottomTrailing
        )
    }
}

// ─── Marginalia "M" badge ──────────────────────────────────────────────────────

private struct BrandMark: View {
    var label: String? = nil

    var body: some View {
        HStack(spacing: 6) {
            ZStack {
                RoundedRectangle(cornerRadius: 5, style: .continuous)
                    .fill(Color.mPrimary)
                    .frame(width: 20, height: 20)
                Text("M")
                    .font(.system(size: 12, weight: .bold, design: .serif))
                    .foregroundStyle(.white)
            }
            if let label {
                Text(label)
                    .font(.system(size: 11, weight: .medium))
                    .foregroundStyle(.secondary)
                    .lineLimit(1)
            }
        }
    }
}

// ════════════════════════════════════════════════════════════════════════════
//  WIDGET 1 — Daily phrase ("frase scelta per te")
// ════════════════════════════════════════════════════════════════════════════

private struct PhraseEntry: TimelineEntry {
    let date: Date
    let text: String
    let bookTitle: String
    let author: String
    let greeting: String
    let weatherMood: String

    static let placeholder = PhraseEntry(
        date: Date(),
        text: "Non si leggono i libri per finirli, ma per abitarli — per trovare in essi un'altra casa.",
        bookTitle: "Come un romanzo",
        author: "Daniel Pennac",
        greeting: "Buongiorno",
        weatherMood: "clear"
    )
}

private struct PhraseProvider: TimelineProvider {
    func placeholder(in context: Context) -> PhraseEntry { .placeholder }

    func getSnapshot(in context: Context, completion: @escaping (PhraseEntry) -> Void) {
        completion(entry())
    }

    func getTimeline(in context: Context, completion: @escaping (Timeline<PhraseEntry>) -> Void) {
        // The Flutter app rewrites the data roughly every 3 hours; refresh a touch
        // sooner so a freshly-picked phrase shows up without waiting a full cycle.
        let next = Calendar.current.date(byAdding: .hour, value: 2, to: Date())!
        completion(Timeline(entries: [entry()], policy: .after(next)))
    }

    private func entry() -> PhraseEntry {
        let d = sharedDefaults()
        return PhraseEntry(
            date: Date(),
            text: d?.string(forKey: "w_text") ?? PhraseEntry.placeholder.text,
            bookTitle: d?.string(forKey: "w_book") ?? PhraseEntry.placeholder.bookTitle,
            author: d?.string(forKey: "w_author") ?? PhraseEntry.placeholder.author,
            greeting: d?.string(forKey: "w_greeting") ?? greetingForNow(),
            weatherMood: d?.string(forKey: "w_weather") ?? "clear"
        )
    }
}

private func greetingForNow() -> String {
    switch Calendar.current.component(.hour, from: Date()) {
    case 5..<12:  return "Buongiorno"
    case 12..<17: return "Buon pomeriggio"
    case 17..<21: return "Buona sera"
    default:      return "Buona notte"
    }
}

private func weatherSystemImage(_ mood: String) -> String {
    switch mood {
    case "sunny":  return "sun.max"
    case "rain":   return "cloud.rain"
    case "cloudy": return "cloud"
    case "snow":   return "snowflake"
    default:       return "moon.stars"
    }
}

private func firstSentence(_ text: String, max: Int) -> String {
    guard text.count > max else { return text }
    let cut = String(text.prefix(max))
    if let dot = cut.lastIndex(of: "."),
       cut.distance(from: cut.startIndex, to: dot) > max * 6 / 10 {
        return String(text[...dot])
    }
    return cut.trimmingCharacters(in: .whitespaces) + "…"
}

private struct PhraseView: View {
    @Environment(\.widgetFamily) var family
    let entry: PhraseEntry

    private var quoteMax: Int {
        switch family {
        case .systemSmall:  return 90
        case .systemMedium: return 140
        default:            return 320
        }
    }

    private var quoteFont: Font {
        switch family {
        case .systemSmall:  return .system(size: 13, weight: .regular, design: .serif).italic()
        case .systemMedium: return .system(size: 14, weight: .regular, design: .serif).italic()
        default:            return .system(size: 17, weight: .regular, design: .serif).italic()
        }
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            HStack {
                BrandMark(label: family == .systemSmall ? nil : entry.greeting)
                Spacer()
                if family != .systemSmall {
                    Image(systemName: weatherSystemImage(entry.weatherMood))
                        .font(.system(size: 13))
                        .foregroundStyle(.secondary)
                }
            }

            Spacer(minLength: 8)

            Text(firstSentence(entry.text, max: quoteMax))
                .font(quoteFont)
                .foregroundStyle(.primary)
                .lineSpacing(family == .systemLarge ? 5 : 3)
                .minimumScaleFactor(0.85)
                .lineLimit(family == .systemSmall ? 5 : (family == .systemMedium ? 4 : 9))
                .fixedSize(horizontal: false, vertical: true)

            Spacer(minLength: 8)

            if family == .systemLarge {
                HStack(spacing: 10) {
                    RoundedRectangle(cornerRadius: 2)
                        .fill(Color.mAccent)
                        .frame(width: 3, height: 30)
                    VStack(alignment: .leading, spacing: 2) {
                        Text(entry.bookTitle)
                            .font(.system(size: 13, weight: .semibold, design: .serif))
                            .foregroundStyle(.primary)
                            .lineLimit(1)
                        Text(entry.author)
                            .font(.system(size: 10, weight: .medium))
                            .foregroundStyle(.secondary)
                            .lineLimit(1)
                    }
                    Spacer()
                }
            } else {
                Text(entry.bookTitle.uppercased())
                    .font(.system(size: 9, weight: .semibold))
                    .foregroundStyle(.secondary)
                    .lineLimit(1)
            }
        }
        .padding(family == .systemSmall ? 13 : 15)
    }
}

struct MarginaliaPhraseWidget: Widget {
    let kind = "MarginaliaWidget" // keep stable: matches w_* keys written by Dart

    var body: some WidgetConfiguration {
        StaticConfiguration(kind: kind, provider: PhraseProvider()) { entry in
            PhraseView(entry: entry)
                .containerBackground(for: .widget) {
                    ZStack {
                        Rectangle().fill(.ultraThinMaterial)
                        GlassTint()
                    }
                }
        }
        .configurationDisplayName("Frase del momento")
        .description("La frase scelta per te, aggiornata durante il giorno.")
        .supportedFamilies([.systemSmall, .systemMedium, .systemLarge])
    }
}

// ════════════════════════════════════════════════════════════════════════════
//  WIDGET 2 — Reading stats
// ════════════════════════════════════════════════════════════════════════════

private struct StatsEntry: TimelineEntry {
    let date: Date
    let streak: Int
    let monthMinutes: Int
    let yearBooks: Int
    let yearGoal: Int

    static let placeholder = StatsEntry(
        date: Date(), streak: 7, monthMinutes: 240, yearBooks: 12, yearGoal: 30
    )
}

private struct StatsProvider: TimelineProvider {
    func placeholder(in context: Context) -> StatsEntry { .placeholder }

    func getSnapshot(in context: Context, completion: @escaping (StatsEntry) -> Void) {
        completion(entry())
    }

    func getTimeline(in context: Context, completion: @escaping (Timeline<StatsEntry>) -> Void) {
        // Stats roll over at midnight; refresh at the next local midnight + a small
        // 2h fallback so the streak stays fresh even if the app isn't opened.
        let cal = Calendar.current
        let nextMidnight = cal.nextDate(after: Date(), matching: DateComponents(hour: 0, minute: 5),
                                        matchingPolicy: .nextTime) ?? cal.date(byAdding: .hour, value: 2, to: Date())!
        completion(Timeline(entries: [entry()], policy: .after(nextMidnight)))
    }

    private func entry() -> StatsEntry {
        let d = sharedDefaults()
        // home_widget stores numbers; read defensively (they may be Int or String).
        func intVal(_ key: String) -> Int {
            if let o = d?.object(forKey: key) {
                if let i = o as? Int { return i }
                if let n = o as? NSNumber { return n.intValue }
                if let s = o as? String, let i = Int(s) { return i }
            }
            return 0
        }
        return StatsEntry(
            date: Date(),
            streak: intVal("w_streak"),
            monthMinutes: intVal("w_month_min"),
            yearBooks: intVal("w_year_books"),
            yearGoal: intVal("w_year_goal")
        )
    }
}

private struct StatTile: View {
    let value: String
    let label: String
    var accent: Bool = false

    var body: some View {
        VStack(alignment: .leading, spacing: 1) {
            Text(value)
                .font(.system(size: 24, weight: .bold, design: .rounded))
                .foregroundStyle(accent ? Color.mPrimary : Color.primary)
                .minimumScaleFactor(0.6)
                .lineLimit(1)
            Text(label.uppercased())
                .font(.system(size: 8.5, weight: .semibold))
                .foregroundStyle(.secondary)
                .lineLimit(1)
        }
    }
}

private struct StatsView: View {
    @Environment(\.widgetFamily) var family
    let entry: StatsEntry

    private func minutesLabel(_ m: Int) -> String {
        if m < 60 { return "\(m) min" }
        let h = m / 60, r = m % 60
        return r == 0 ? "\(h)h" : "\(h)h \(r)m"
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            BrandMark(label: family == .systemSmall ? nil : "La tua lettura")
            Spacer(minLength: 10)

            if family == .systemSmall {
                StatTile(value: "\(entry.streak)", label: "giorni di fila", accent: true)
                Spacer(minLength: 8)
                Text(minutesLabel(entry.monthMinutes) + " questo mese")
                    .font(.system(size: 10, weight: .medium))
                    .foregroundStyle(.secondary)
                    .lineLimit(1)
            } else {
                HStack(alignment: .top, spacing: 14) {
                    StatTile(value: "\(entry.streak)", label: "giorni di fila", accent: true)
                    StatTile(value: minutesLabel(entry.monthMinutes), label: "questo mese")
                    if entry.yearGoal > 0 {
                        StatTile(value: "\(entry.yearBooks)/\(entry.yearGoal)", label: "libri / obiettivo")
                    } else {
                        StatTile(value: "\(entry.yearBooks)", label: "libri quest'anno")
                    }
                }
                if entry.yearGoal > 0 {
                    Spacer(minLength: 10)
                    GoalBar(progress: min(1, Double(entry.yearBooks) / Double(max(1, entry.yearGoal))))
                }
            }
        }
        .padding(15)
    }
}

private struct GoalBar: View {
    let progress: Double
    var body: some View {
        GeometryReader { geo in
            ZStack(alignment: .leading) {
                Capsule().fill(Color.mMuted.opacity(0.25))
                Capsule().fill(Color.mPrimary)
                    .frame(width: max(4, geo.size.width * progress))
            }
        }
        .frame(height: 6)
    }
}

struct MarginaliaStatsWidget: Widget {
    let kind = "MarginaliaStats"

    var body: some WidgetConfiguration {
        StaticConfiguration(kind: kind, provider: StatsProvider()) { entry in
            StatsView(entry: entry)
                .containerBackground(for: .widget) {
                    ZStack {
                        Rectangle().fill(.ultraThinMaterial)
                        GlassTint()
                    }
                }
        }
        .configurationDisplayName("Statistiche di lettura")
        .description("Streak, minuti del mese e libri dell'anno.")
        .supportedFamilies([.systemSmall, .systemMedium])
    }
}

// ════════════════════════════════════════════════════════════════════════════
//  Bundle entry point
// ════════════════════════════════════════════════════════════════════════════

@main
struct MarginaliaWidgetBundle: WidgetBundle {
    var body: some Widget {
        MarginaliaPhraseWidget()
        MarginaliaStatsWidget()
    }
}
